openapi: "3.1.0"
info:
  title: "Sykepenger inntektsmelding lps API"
  description: "API for å hente forespørsler og inntektsmeldinger for sykepenger"
  version: "1.0.0"

security:
  - bearerAuth: [ ]
paths:
  /v1/forespoersler:
    get:
      description: "Hent forespørsler for tilhørende systembrukers orgnr."
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ForespoerselResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av forespørsler"
    post:
      description: "Hent forespørsler for tilhørende systembrukers orgnr, filtrer\
        \ basert på request."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForespoerselRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ForespoerselResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av forespørsler"
  /v1/inntektsmelding:
    post:
      description: "Send inn inntektsmelding"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SkjemaInntektsmelding"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "string"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "En feil oppstod"
  /v1/inntektsmeldinger:
    get:
      description: "Hent alle inntektsmeldinger for tilhørende systembrukers orgnr"
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/InntektsmeldingResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Ingen inntektsmeldinger funnet"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av inntektsmeldinger"
    post:
      description: "Hent inntektsmeldinger for tilhørende systembrukers orgnr, filtrer\
        \ basert på request"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InntektsmeldingRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/InntektsmeldingResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Ingen inntektsmeldinger funnet"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av inntektsmeldinger"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Periode:
      type: "object"
      properties:
        fom:
          type: "string"
          format: "date"
        tom:
          type: "string"
          format: "date"
      required:
      - "fom"
      - "tom"
    Forespoersel:
      type: "object"
      properties:
        forespoersel_id:
          type: "string"
        orgnr:
          type: "string"
        fnr:
          type: "string"
        status:
          type: "string"
          enum:
          - "AKTIV"
          - "MOTTATT"
          - "FORKASTET"
        sykmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        egenmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        arbeidsgiverperiode_paakrevd:
          type: "boolean"
        inntekt_paakrevd:
          type: "boolean"
      required:
      - "forespoersel_id"
      - "orgnr"
      - "fnr"
      - "status"
      - "sykmeldingsperioder"
      - "egenmeldingsperioder"
    ForespoerselResponse:
      type: "object"
      properties:
        antall:
          type: "integer"
          format: "int32"
        forespoersler:
          type: "array"
          items:
            $ref: "#/components/schemas/Forespoersel"
      required:
      - "forespoersler"
    ForespoerselRequest:
      type: "object"
      properties:
        fnr:
          type: "string"
        forespoersel_id:
          type: "string"
        status:
          type: "string"
          enum:
          - "AKTIV"
          - "MOTTATT"
          - "FORKASTET"
    RedusertLoennIAgp:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        begrunnelse:
          type: "string"
          enum:
          - "ArbeidOpphoert"
          - "BeskjedGittForSent"
          - "BetvilerArbeidsufoerhet"
          - "FerieEllerAvspasering"
          - "FiskerMedHyre"
          - "FravaerUtenGyldigGrunn"
          - "IkkeFravaer"
          - "IkkeFullStillingsandel"
          - "IkkeLoenn"
          - "LovligFravaer"
          - "ManglerOpptjening"
          - "Permittering"
          - "Saerregler"
          - "StreikEllerLockout"
          - "TidligereVirksomhet"
      required:
      - "begrunnelse"
    Arbeidsgiverperiode:
      type: "object"
      properties:
        perioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        egenmeldinger:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        redusertLoennIAgp:
          $ref: "#/components/schemas/RedusertLoennIAgp"
      required:
      - "perioder"
      - "egenmeldinger"
    Naturalytelse:
      type: "object"
      properties:
        naturalytelse:
          type: "string"
          enum:
          - "AKSJERGRUNNFONDSBEVISTILUNDERKURS"
          - "ANNET"
          - "BEDRIFTSBARNEHAGEPLASS"
          - "BESOEKSREISERHJEMMETANNET"
          - "BIL"
          - "BOLIG"
          - "ELEKTRONISKKOMMUNIKASJON"
          - "FRITRANSPORT"
          - "INNBETALINGTILUTENLANDSKPENSJONSORDNING"
          - "KOSTBESPARELSEIHJEMMET"
          - "KOSTDAGER"
          - "KOSTDOEGN"
          - "LOSJI"
          - "OPSJONER"
          - "RENTEFORDELLAAN"
          - "SKATTEPLIKTIGDELFORSIKRINGER"
          - "TILSKUDDBARNEHAGEPLASS"
          - "YRKEBILTJENESTLIGBEHOVKILOMETER"
          - "YRKEBILTJENESTLIGBEHOVLISTEPRIS"
        verdiBeloep:
          type: "number"
          format: "double"
        sluttdato:
          type: "string"
          format: "date"
      required:
      - "naturalytelse"
      - "sluttdato"
    InntektEndringAarsak:
      type: "object"
      properties: {}
    Inntekt:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        inntektsdato:
          type: "string"
          format: "date"
        naturalytelser:
          type: "array"
          items:
            $ref: "#/components/schemas/Naturalytelse"
        endringAarsak:
          $ref: "#/components/schemas/InntektEndringAarsak"
      required:
      - "inntektsdato"
      - "naturalytelser"
    RefusjonEndring:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        startdato:
          type: "string"
          format: "date"
      required:
      - "startdato"
    Refusjon:
      type: "object"
      properties:
        beloepPerMaaned:
          type: "number"
          format: "double"
        endringer:
          type: "array"
          items:
            $ref: "#/components/schemas/RefusjonEndring"
        sluttdato:
          type: "string"
          format: "date"
      required:
      - "endringer"
    SkjemaInntektsmelding:
      type: "object"
      properties:
        forespoerselId:
          type: "string"
          format: "uuid"
        avsenderTlf:
          type: "string"
        agp:
          $ref: "#/components/schemas/Arbeidsgiverperiode"
        inntekt:
          $ref: "#/components/schemas/Inntekt"
        refusjon:
          $ref: "#/components/schemas/Refusjon"
      required:
      - "forespoerselId"
      - "avsenderTlf"
    Type:
      type: "object"
      properties: {}
    Sykmeldt:
      type: "object"
      properties:
        navn:
          type: "string"
      required:
      - "navn"
    Avsender:
      type: "object"
      properties:
        orgNavn:
          type: "string"
        navn:
          type: "string"
        tlf:
          type: "string"
      required:
      - "orgNavn"
      - "navn"
      - "tlf"
    Inntektsmelding:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          $ref: "#/components/schemas/Type"
        sykmeldt:
          $ref: "#/components/schemas/Sykmeldt"
        avsender:
          $ref: "#/components/schemas/Avsender"
        sykmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        agp:
          $ref: "#/components/schemas/Arbeidsgiverperiode"
        inntekt:
          $ref: "#/components/schemas/Inntekt"
        refusjon:
          $ref: "#/components/schemas/Refusjon"
        aarsakInnsending:
          type: "string"
          enum:
          - "Ny"
          - "Endring"
        mottatt:
          type: "string"
          format: "date-time"
        vedtaksperiodeId:
          type: "string"
          format: "uuid"
      required:
      - "id"
      - "type"
      - "sykmeldt"
      - "avsender"
      - "sykmeldingsperioder"
      - "aarsakInnsending"
      - "mottatt"
    InnsendtInntektsmelding:
      type: "object"
      properties:
        dokument:
          $ref: "#/components/schemas/Inntektsmelding"
        orgnr:
          type: "string"
        fnr:
          type: "string"
        foresporsel_id:
          type: "string"
        innsendt_tid:
          type: "string"
          format: "date-time"
        mottatt_tid:
          type: "string"
          format: "date-time"
      required:
      - "dokument"
      - "orgnr"
      - "fnr"
      - "innsendt_tid"
      - "mottatt_tid"
    InntektsmeldingResponse:
      type: "object"
      properties:
        antall:
          type: "integer"
          format: "int32"
        inntektsmeldinger:
          type: "array"
          items:
            $ref: "#/components/schemas/InnsendtInntektsmelding"
      required:
      - "inntektsmeldinger"
    InntektsmeldingRequest:
      type: "object"
      properties:
        fnr:
          type: "string"
        foresporsel_id:
          type: "string"
        fra_dato:
          type: "string"
          format: "date-time"
        til_dato:
          type: "string"
          format: "date-time"