openapi: "3.1.0"
info:
  title: "Sykepenger inntektsmelding lps API"
  description: "API for å hente forespørsler og inntektsmeldinger for sykepenger"
  version: "1.0.0"

security:
  - bearerAuth: [ ]
paths:
  /v1/forespoersler:
    get:
      description: "Hent forespørsler for tilhørende systembrukers orgnr."
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ForespoerselResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av forespørsler"
    post:
      description: "Hent forespørsler for tilhørende systembrukers orgnr, filtrer\
        \ basert på request."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForespoerselRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ForespoerselResponse"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av forespørsler"
  /v1/inntektsmelding:
    post:
      description: "Send inn inntektsmelding"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InntektsmeldingRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "En feil oppstod"
  /v1/inntektsmeldinger:
    get:
      description: "Hent alle inntektsmeldinger for tilhørende systembrukers orgnr"
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/InntektsmeldingFilterResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Ingen inntektsmeldinger funnet"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av inntektsmeldinger"
    post:
      description: "Hent inntektsmeldinger for tilhørende systembrukers orgnr, filtrer\
        \ basert på request"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InntektsmeldingFilterRequest"
        required: true
      responses:
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
                Example#2:
                  value: "Uautorisert tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/InntektsmeldingFilterResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Ingen inntektsmeldinger funnet"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Feil ved henting av inntektsmeldinger"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Periode:
      type: "object"
      properties:
        fom:
          type: "string"
          format: "date"
        tom:
          type: "string"
          format: "date"
      required:
      - "fom"
      - "tom"
    Forespoersel:
      type: "object"
      properties:
        navReferanseId:
          type: "string"
          format: "uuid"
        orgnr:
          type: "string"
        fnr:
          type: "string"
        status:
          type: "string"
          enum:
          - "AKTIV"
          - "BESVART"
          - "FORKASTET"
        sykmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        egenmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        arbeidsgiverperiodePaakrevd:
          type: "boolean"
        inntektPaakrevd:
          type: "boolean"
      required:
      - "navReferanseId"
      - "orgnr"
      - "fnr"
      - "status"
      - "sykmeldingsperioder"
      - "egenmeldingsperioder"
      - "arbeidsgiverperiodePaakrevd"
      - "inntektPaakrevd"
    ForespoerselResponse:
      type: "object"
      properties:
        antall:
          type: "integer"
          format: "int32"
        forespoersler:
          type: "array"
          items:
            $ref: "#/components/schemas/Forespoersel"
      required:
      - "antall"
      - "forespoersler"
    ForespoerselRequest:
      type: "object"
      properties:
        fnr:
          type: "string"
        navReferanseId:
          type: "string"
          format: "uuid"
        status:
          type: "string"
          enum:
          - "AKTIV"
          - "BESVART"
          - "FORKASTET"
    RedusertLoennIAgp:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        begrunnelse:
          type: "string"
          enum:
          - "ArbeidOpphoert"
          - "BeskjedGittForSent"
          - "BetvilerArbeidsufoerhet"
          - "FerieEllerAvspasering"
          - "FiskerMedHyre"
          - "FravaerUtenGyldigGrunn"
          - "IkkeFravaer"
          - "IkkeFullStillingsandel"
          - "IkkeLoenn"
          - "LovligFravaer"
          - "ManglerOpptjening"
          - "Permittering"
          - "Saerregler"
          - "StreikEllerLockout"
          - "TidligereVirksomhet"
      required:
      - "beloep"
      - "begrunnelse"
    Arbeidsgiverperiode:
      type: "object"
      properties:
        perioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        egenmeldinger:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        redusertLoennIAgp:
          $ref: "#/components/schemas/RedusertLoennIAgp"
      required:
      - "perioder"
      - "egenmeldinger"
    Naturalytelse:
      type: "object"
      properties:
        naturalytelse:
          type: "string"
          enum:
          - "AKSJERGRUNNFONDSBEVISTILUNDERKURS"
          - "ANNET"
          - "BEDRIFTSBARNEHAGEPLASS"
          - "BESOEKSREISERHJEMMETANNET"
          - "BIL"
          - "BOLIG"
          - "ELEKTRONISKKOMMUNIKASJON"
          - "FRITRANSPORT"
          - "INNBETALINGTILUTENLANDSKPENSJONSORDNING"
          - "KOSTBESPARELSEIHJEMMET"
          - "KOSTDAGER"
          - "KOSTDOEGN"
          - "LOSJI"
          - "OPSJONER"
          - "RENTEFORDELLAAN"
          - "SKATTEPLIKTIGDELFORSIKRINGER"
          - "TILSKUDDBARNEHAGEPLASS"
          - "YRKEBILTJENESTLIGBEHOVKILOMETER"
          - "YRKEBILTJENESTLIGBEHOVLISTEPRIS"
        verdiBeloep:
          type: "number"
          format: "double"
        sluttdato:
          type: "string"
          format: "date"
      required:
      - "naturalytelse"
      - "verdiBeloep"
      - "sluttdato"
    InntektEndringAarsak:
      type: "object"
      oneOf:
        - $ref: "#/components/schemas/Bonus"
        - $ref: "#/components/schemas/Feilregistrert"
        - $ref: "#/components/schemas/Ferie"
        - $ref: "#/components/schemas/Ferietrekk"
        - $ref: "#/components/schemas/Nyansatt"
        - $ref: "#/components/schemas/NyStilling"
        - $ref: "#/components/schemas/NyStillingsprosent"
        - $ref: "#/components/schemas/Permisjon"
        - $ref: "#/components/schemas/Permittering"
        - $ref: "#/components/schemas/Sykefravaer"
        - $ref: "#/components/schemas/Tariffendring"
        - $ref: "#/components/schemas/VarigLoennsendring"
    Bonus:
      title: "Bonus"
      properties:
        aarsak:
          type: "string"
          enum:
            - Bonus
    Feilregistrert:
      title: "Feilregistrert"
      properties:
        aarsak:
          type: "string"
          enum:
            - Feilregistrert
    Tariffendring:
      title: "Tariffendring"
      required:
        - gjelderFra
        - bleKjent
      properties:
        aarsak:
          type: "string"
          enum:
            - Tariffendring
        gjelderFra:
          type: string
          format: date
        bleKjent:
          type: string
          format: date
    Sykefravaer:
      title: "Sykefravaer"
      required:
        - sykefravaer
      properties:
        aarsak:
          type: "string"
          enum:
            - Sykefravaer
        sykefravaer:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Ferie:
      title: "Ferie"
      required:
        - ferier
      properties:
        aarsak:
          type: "string"
          enum:
            - Ferie
        ferier:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Ferietrekk:
      title: "Ferietrekk"
      properties:
        aarsak:
          type: "string"
          enum:
            - Ferietrekk
    Nyansatt:
      title: "Nyansatt"
      properties:
        aarsak:
          type: "string"
          enum:
            - Nyansatt
    NyStilling:
      title: "NyStilling"
      requred:
        - gjelderFra
      properties:
        aarsak:
          type: "string"
          enum:
            - NyStilling
        gjelderFra:
          type: string
          format: date
    NyStillingsprosent:
      title: "NyStillingsprosent"
      required:
        -gjelderFra
      properties:
        aarsak:
          type: "string"
          enum:
            - NyStillingsprosent
        gjelderFra:
          type: string
          format: date
    Permisjon:
      title: "Permisjon"
      required:
        - permisjoner
      properties:
        aarsak:
          type: "string"
          enum:
            - Permisjon
        permisjoner:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Permittering:
      title: "Permittering"
      required:
        - permitteringer
      properties:
        aarsak:
          type: "string"
          enum:
            - Permittering
        permitteringer:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    VarigLoennsendring:
      title: "VarigLoennsendring"
      required:
        -gjelderFra
      properties:
        aarsak:
          type: "string"
          enum:
            - VarigLoennsendring
        gjelderFra:
          type: string
          format: date

    Inntekt:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        inntektsdato:
          type: "string"
          format: "date"
        naturalytelser:
          type: "array"
          items:
            $ref: "#/components/schemas/Naturalytelse"
        endringAarsak:
          $ref: "#/components/schemas/InntektEndringAarsak"
        endringAarsaker:
          type: "array"
          items:
            $ref: "#/components/schemas/InntektEndringAarsak"
      required:
      - "beloep"
      - "inntektsdato"
      - "naturalytelser"
    RefusjonEndring:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        startdato:
          type: "string"
          format: "date"
      required:
      - "beloep"
      - "startdato"
    Refusjon:
      type: "object"
      properties:
        beloepPerMaaned:
          type: "number"
          format: "double"
        endringer:
          type: "array"
          items:
            $ref: "#/components/schemas/RefusjonEndring"
        sluttdato:
          type: "string"
          format: "date"
      required:
      - "beloepPerMaaned"
      - "endringer"
    Avsender:
      type: "object"
      properties:
        systemNavn:
          type: "string"
        systemVersjon:
          type: "string"
      required:
      - "systemNavn"
      - "systemVersjon"
    InntektsmeldingRequest:
      type: "object"
      properties:
        navReferanseId:
          type: "string"
          format: "uuid"
        agp:
          $ref: "#/components/schemas/Arbeidsgiverperiode"
        inntekt:
          $ref: "#/components/schemas/Inntekt"
        refusjon:
          $ref: "#/components/schemas/Refusjon"
        sykmeldtFnr:
          type: "string"
        arbeidsgiverTlf:
          type: "string"
        aarsakInnsending:
          type: "string"
          enum:
          - "Ny"
          - "Endring"
        avsender:
          $ref: "#/components/schemas/Avsender"
      required:
      - "navReferanseId"
      - "sykmeldtFnr"
      - "arbeidsgiverTlf"
      - "aarsakInnsending"
      - "avsender"
    Arbeidsgiver:
      type: "object"
      properties:
        orgnr:
          type: "string"
        tlf:
          type: "string"
      required:
      - "orgnr"
      - "tlf"
    InntektsmeldingResponse:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        navReferanseId:
          type: "string"
          format: "uuid"
        agp:
          $ref: "#/components/schemas/Arbeidsgiverperiode"
        inntekt:
          $ref: "#/components/schemas/Inntekt"
        refusjon:
          $ref: "#/components/schemas/Refusjon"
        sykmeldtFnr:
          type: "string"
        aarsakInnsending:
          type: "string"
          enum:
          - "Ny"
          - "Endring"
        typeInnsending:
          type: "string"
          enum:
          - "FORESPURT"
          - "ARBEIDSGIVER_INITIERT"
          - "FORESPURT_EKSTERN"
        innsendtTid:
          type: "string"
          format: "date-time"
        versjon:
          type: "integer"
          format: "int32"
        arbeidsgiver:
          $ref: "#/components/schemas/Arbeidsgiver"
        avsender:
          $ref: "#/components/schemas/Avsender"
        status:
          type: "string"
          enum:
          - "MOTTATT"
          - "UNDER_BEHANDLING"
          - "FEILET"
          - "GODKJENT"
        statusMelding:
          type: "string"
      required:
      - "id"
      - "navReferanseId"
      - "sykmeldtFnr"
      - "aarsakInnsending"
      - "typeInnsending"
      - "innsendtTid"
      - "versjon"
      - "arbeidsgiver"
      - "avsender"
      - "status"
    InntektsmeldingFilterResponse:
      type: "object"
      properties:
        antall:
          type: "integer"
          format: "int32"
        inntektsmeldinger:
          type: "array"
          items:
            $ref: "#/components/schemas/InntektsmeldingResponse"
      required:
      - "antall"
      - "inntektsmeldinger"
    InntektsmeldingFilterRequest:
      type: "object"
      properties:
        fnr:
          type: "string"
        navReferanseId:
          type: "string"
          format: "uuid"
        fraTid:
          type: "string"
          format: "date-time"
        tilTid:
          type: "string"
          format: "date-time"
