apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  leaderElection: true
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: secure_logs
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  ingresses:
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
    - https://sykepenger-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: platform.tt02.altinn.no
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: helse
          separator: "/"
          name: im.read
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: helseytelser
          separator: "/"
          name: sykepenger
      consumes:
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: hag-lps
  envFrom:
    - secret: altinn-subscription
    - secret: sykepenger-im-lps-api-unleash-api-token
  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helse/im.read nav:helseytelser/sykepenger"
    - name: ALTINN_3_BASE_URL
      value: "https://platform.tt02.altinn.no"
    - name: ALTINN_IM_RESSURS
      value: "nav_system_sykepenger_inntektsmelding"
    - name: ALTINN_PDP_SCOPE
      value: "altinn:authorization/authorize"
    - name: NAV_ARBEIDSGIVER_PORTAL_BASEURL
      value: "https://arbeidsgiver.intern.dev.nav.no"
    - name: NAV_ARBEIDSGIVER_API_BASEURL
      value: "https://sykepenger-im-lps-api.ekstern.dev.nav.no"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"

