apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  ingresses:
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: platform.tt02.altinn.no
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          enabled: true
          product: helse
          separator: "/"
          name: im.read
      consumes:
        - name: "altinn:authorization/authorize"
        - name: "digdir:dialogporten.serviceprovider"

  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: hag-lps
  envFrom:
    - secret: altinn-subscription
  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helse/im.read"
    - name: ALTINN_3_BASE_URL
      value: "https://platform.tt02.altinn.no"
    - name: ALTINN_IM_RESSURS
      value: "nav_sykepenger_inntektsmelding-nedlasting"
    - name: ALTINN_PDP_SCOPE
      value: "altinn:authorization/authorize"
    - name: DIALOGPORTEN_SCOPE
      value: "digdir:dialogporten.serviceprovider"
    - name: NAV_ARBEIDSGIVER_PORTAL_BASEURL
      value: "https://arbeidsgiver.intern.dev.nav.no"

