apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
spec:
  leaderElection: true
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  kafka:
    pool: nav-dev
  ingresses:
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
    - https://sykepenger-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: platform.tt02.altinn.no
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: helsearbeidsgiver-pdfgen.intern.dev.nav.no
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: helseytelser
          separator: "/"
          name: sykepenger
      consumes:
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: hag-lps
            users:
              - name: lps_api_datastream_bruker
  envFrom:
    - secret: altinn-subscription
    - secret: sykepenger-im-lps-api-unleash-api-token
  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helseytelser/sykepenger"
    - name: ALTINN_3_BASE_URL
      value: "https://platform.tt02.altinn.no"
    - name: ALTINN_IM_RESSURS
      value: "nav_sykepenger_inntektsmelding"
    - name: ALTINN_SM_RESSURS
      value: "nav_sykepenger_sykmelding"
    - name: ALTINN_SOEKNAD_RESSURS
      value: "nav_sykepenger_soeknad"
    - name: ALTINN_PDP_SCOPE
      value: "altinn:authorization/authorize"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDFGEN_SYKMELDING_URL
      value: "https://helsearbeidsgiver-pdfgen.intern.dev.nav.no/api/v1/genpdf/sykmelding/sykmelding"
