apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  leaderElection: true
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: secure_logs
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
#  ingresses:
#    - https://sykepenger-api.ekstern.nav.no
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
#        - host: platform.altinn.no
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: helse
          separator: "/"
          name: im.read
      consumes:
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
        databases:
          - name: hag-lps
  envFrom:
    - secret: sykepenger-im-lps-api-unleash-api-token
#    - secret: altinn-subscription
  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helse/im.read"
#    - name: ALTINN_3_BASE_URL
#      value: "https://platform.altinn.no"
#    - name: ALTINN_IM_RESSURS
#      value: "nav_sykepenger_inntektsmelding-nedlasting"
#    - name: ALTINN_PDP_SCOPE
#      value: "altinn_authorization/authorize"

