apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
  annotations:
    texas.nais.io/enabled: "true"
spec:
  leaderElection: true
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "1536Mi"
    limits:
      memory: "2048Mi"
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  kafka:
    pool: nav-prod
#  ingresses:
#    - https://sykepenger-api.ekstern.nav.no
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
#        - host: platform.altinn.no
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: helseytelser
          separator: "/"
          name: sykepenger
      consumes:
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-3840
        diskAutoresize: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: hag-lps
            users:
              - name: lps_api_datastream_bruker
  envFrom:
    - secret: sykepenger-im-lps-api-unleash-api-token
#    - secret: altinn-subscription
  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helseytelser/sykepenger"
#    - name: ALTINN_3_BASE_URL
#      value: "https://platform.altinn.no"
    - name: ALTINN_IM_RESSURS
      value: "nav_sykepenger_inntektsmelding"
    - name: ALTINN_SM_RESSURS
      value: "nav_sykepenger_sykmelding"
    - name: ALTINN_SOKNAD_RESSURS
      value: "nav_sykepenger_soeknad"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
#    - name: ALTINN_PDP_SCOPE
#      value: "altinn_authorization/authorize"

