apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: helsearbeidsgiver
  secretName: sykepenger-im-lps-api-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development
