openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Localhost
  - url: https://sykepenger-im-lps-api.dev-gcp.nav.cloud.nais.io
    description: Dev
  - url: https://sykepenger-im-lps-api.ekstern.dev.nav.no
    description: Dev Ekstern
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Periode:
      type: "object"
      properties:
        fom:
          type: "string"
          format: "date"
        tom:
          type: "string"
          format: "date"
      required:
        - "fom"
        - "tom"
    Arbeidsgiverperiode:
      type: "object"
      properties:
        perioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        egenmeldinger:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        redusertLoennIAgp:
          $ref: "#/components/schemas/RedusertLoennIAgp"
      required:
        - "perioder"
        - "egenmeldinger"
    ForslagInntekt:
      type: "object"
      properties: { }
    Inntekt:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        inntektsdato:
          type: "string"
          format: "date"
        naturalytelser:
          type: "array"
          items:
            $ref: "#/components/schemas/Naturalytelse"
        endringAarsak:
          $ref: "#/components/schemas/InntektEndringAarsak"
      required:
        - "inntektsdato"
        - "naturalytelser"
    ForslagRefusjon:
      type: "object"
      properties:
        perioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        opphoersdato:
          type: "string"
          format: "date"
      required:
        - "perioder"
    Refusjon:
      type: "object"
      properties:
        beloepPerMaaned:
          type: "number"
          format: "double"
        endringer:
          type: "array"
          items:
            $ref: "#/components/schemas/RefusjonEndring"
        sluttdato:
          type: "string"
          format: "date"
      required:
        - "endringer"
    Forespoersel:
      type: "object"
      properties:
        forespoerselId:
          type: "string"
          format: "uuid"
        orgnr:
          type: "string"
        fnr:
          type: "string"
        status:
          type: string
          enum:
            - AKTIV
            - MOTTATT
            - FORKASTET
          description: "Status på forespørsel om inntektsmelding. AKTIV = Nav venter på inntektsmelding, MOTTATT = Nav har mottatt, FORKASTET = Nav trenger ikke lenger inntektsmelding. 
          Merk at status ikke alltid oppdateres umiddelbart til MOTTATT etter innsending, dette kan ta inntil en time."
    Type:
      type: "object"
      properties: { }
    Sykmeldt:
      type: "object"
      properties:
        navn:
          type: "string"
      required:
        - "navn"
    Avsender:
      type: "object"
      properties:
        orgNavn:
          type: "string"
        navn:
          type: "string"
        tlf:
          type: "string"
      required:
        - "orgNavn"
        - "navn"
        - "tlf"
    RedusertLoennIAgp:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        begrunnelse:
          type: "string"
          enum:
            - "ArbeidOpphoert"
            - "BeskjedGittForSent"
            - "BetvilerArbeidsufoerhet"
            - "FerieEllerAvspasering"
            - "FiskerMedHyre"
            - "FravaerUtenGyldigGrunn"
            - "IkkeFravaer"
            - "IkkeFullStillingsandel"
            - "IkkeLoenn"
            - "LovligFravaer"
            - "ManglerOpptjening"
            - "Permittering"
            - "Saerregler"
            - "StreikEllerLockout"
            - "TidligereVirksomhet"
      required:
        - "begrunnelse"
    Naturalytelse:
      type: "object"
      properties:
        naturalytelse:
          type: "string"
          enum:
            - "AKSJERGRUNNFONDSBEVISTILUNDERKURS"
            - "ANNET"
            - "BEDRIFTSBARNEHAGEPLASS"
            - "BESOEKSREISERHJEMMETANNET"
            - "BIL"
            - "BOLIG"
            - "ELEKTRONISKKOMMUNIKASJON"
            - "FRITRANSPORT"
            - "INNBETALINGTILUTENLANDSKPENSJONSORDNING"
            - "KOSTBESPARELSEIHJEMMET"
            - "KOSTDAGER"
            - "KOSTDOEGN"
            - "LOSJI"
            - "OPSJONER"
            - "RENTEFORDELLAAN"
            - "SKATTEPLIKTIGDELFORSIKRINGER"
            - "TILSKUDDBARNEHAGEPLASS"
            - "YRKEBILTJENESTLIGBEHOVKILOMETER"
            - "YRKEBILTJENESTLIGBEHOVLISTEPRIS"
        verdiBeloep:
          type: "number"
          format: "double"
        sluttdato:
          type: "string"
          format: "date"
      required:
        - "naturalytelse"
        - "sluttdato"
    InntektEndringAarsak:
      type: "object"
      properties: { }
    RefusjonEndring:
      type: "object"
      properties:
        beloep:
          type: "number"
          format: "double"
        startdato:
          type: "string"
          format: "date"
      required:
        - "startdato"
    Inntektsmelding:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          $ref: "#/components/schemas/Type"
        sykmeldt:
          $ref: "#/components/schemas/Sykmeldt"
        avsender:
          $ref: "#/components/schemas/Avsender"
        sykmeldingsperioder:
          type: "array"
          items:
            $ref: "#/components/schemas/Periode"
        agp:
          $ref: "#/components/schemas/Arbeidsgiverperiode"
        inntekt:
          $ref: "#/components/schemas/Inntekt"
        refusjon:
          $ref: "#/components/schemas/Refusjon"
        aarsakInnsending:
          type: "string"
          enum:
            - "Ny"
            - "Endring"
        mottatt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "type"
        - "sykmeldt"
        - "avsender"
        - "sykmeldingsperioder"
        - "aarsakInnsending"
        - "mottatt"
    InntektsmeldingRequest:
      type: "object"
      properties:
        foresporselid:
          type: "string"
        fnr:
          type: "string"
        datoFom:
          type: "string"
          format: "date"
        datoTom:
          type: "string"
          format: "date"
security:
  - bearerAuth: [ ]
paths:
  /forespoersler:
    get:
      summary: Returns a list of forespørsler.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A JSON array of forespørsel
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Forespoersel"
  /inntektsmeldinger:
    get:
      summary: Returns a list of Inntektsmeldinger.
      description: ""
      responses:
        "200":
          description: A JSON array of Inntektsmelding
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Inntektsmelding"
    post:
      summary: Filterer Inntektsmeldinger based on the request.
      description: ""
      parameters:
        - in: query
          name: foresporselid
          schema:
            type: string
        - in: query
          name: fnr
          schema:
            type: string
        - in: query
          name: datoFom
          schema:
            type: string
            format: date
        - in: query
          name: datoTom
          schema:
            type: string
            format: date
      responses:
        "200":
          description: JSON array of filtered Inntektsmeldinger
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Inntektsmelding"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: "Consumer orgnr mangler"

