services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    environment:
      JSON_CONFIG: '{
          "tokenCallbacks": [
              {
                  "issuerId": "maskinporten",
                  "tokenExpiry": 1200,
                  "requestMappings": [
                      {
                          "requestParam": "scope",
                          "match": "nav:helseytelser/sykepenger",
                          "claims": {
                              "authorization_details": [
                                {
                                  "type": "urn:altinn:systemuser",
                                  "systemuser_org": {
                                    "authority": "iso6523-actorid-upis",
                                    "ID": "0192:315587336"
                                  },
                                  "systemuser_id": [
                                    "38dc7f47-3ff2-4478-8b48-f791ed324c5b"
                                  ],
                                  "system_id": "315339138_tigersys2"
                                }
                              ],
                             "consumer" : {
                                "authority" : "iso6523-actorid-upis",
                                "ID" : "0192:810007842"
                              },
                              "scope": "nav:helseytelser/sykepenger",
                              "sub": "testid",
                              "aud": "nav:helseytelser/sykepenger"
                          }
                      }
                  ]
              }        
          ]
      }'
    ports:
      - "33445:8080"

  kafka:
    image: apache/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"

  lpsapi-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lpsapi
      - POSTGRES_PASSWORD=lpsapi
      - POSTGRES_DB=lpsapi
