services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    environment:
      JSON_CONFIG: '{
          "tokenCallbacks": [
              {
                  "issuerId": "maskinporten",
                  "tokenExpiry": 1200,
                  "requestMappings": [
                      {
                          "requestParam": "scope",
                          "match": "nav:inntektsmelding/lps.write",
                          "claims": {
                              "supplier" : {
                                "authority" : "iso6523-actorid-upis",
                                "ID" : "0192:991825827"
                              },
                             "consumer" : {
                                "authority" : "iso6523-actorid-upis",
                                "ID" : "0192:810007842"
                              },
                              "scope": "nav:inntektsmelding/lps.write",
                              "sub": "testid",
                              "aud": "nav:inntektsmelding/lps.write"
                          }
                      }
                  ]
              }        
          ]
      }'
    ports:
      - "33445:8080"

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"

  lpsapi-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lpsapi
      - POSTGRES_PASSWORD=lpsapi
      - POSTGRES_DB=lpsapi